### ISSUE TITLE
use pingpong-labs/menus in pingpong-labs/module

### ISSUE THREAD

**Issue by ahmadina** [pingpong-labs/modules#80] opened 2014-12-18 14:18 UTC
Hi, How to use pingpong-labs/menus in pingpong-labs/module? 
I have module category and i want use facade category in menu.php in the app/ ,How can I do it ?

**Comment by noxify** [comment] 2015-01-14 17:03
@ahmadina - can we close this issue?

**Comment by noxify** [comment] 2015-01-17 18:28
Hi @ahmadina,

now I think I unterstood your problem correct, because I had the same problem :)

Since I'm not using the Admin Package, I was not able to attach menu entry.

My screnario is/was the following:

I have a module named "Admin", in this module the admin menu is defined with:

```Menu::create('admin-menu', function() ... ```

I have also a module named "Users" which will be loaded after the admin module.
If I try to append a menu link to the `admin-menu` via

```
$leftMenu = Menu::instance('admin-menu');

$leftMenu->url("#", "Test Link");
```

It doesn't work.

An `\Debugbar::info($leftMenu);` returns `null` instead of the existing Menu Object.

Anyway.. I solved the problem with the following.

1. Create a file named `menus.php` in the `app` directory.
2. Add your menu create statements inside like
```
<?php

Menu::create('admin-menu', function ($menu)
{
    $menu->setPresenter('Modules\Admin\Presenters\SidebarMenuPresenter');
});
```

3. In your module create a new file `menus.php`
4. Add the following code in the file
```
$adminLeftMenu = \Menu::instance('admin-menu');



$adminLeftMenu->dropdown('Users', function ($sub) 
	{
		$sub->url("#", "Test");
    	//$sub->route('admin.products.index', 'All Products');
    	//$sub->route('admin.products.create', 'Add New');
	},
	[ 'icon' => 'glyphicon glyphicon-list-alt']
);
```

5. Add the `Modules/<modulename>/menus.php` into the module.json like this:
```
{
    "name": "Users",
    "alias": "users",
    "description": "",
    "keywords": [],
    "active": 1,
    "priority": 1,
    "providers": [],
    "aliases": {},
    "files": [
        "start.php",
        "menus.php"
    ]
}
``` 

Now you have to refresh your browser and it's working...

@gravitano - please correct me, if I'm wrong or if there is an other way to solve this.


Hope this helps :)

**Comment by nWidart** [comment] 2015-01-17 20:09
Hm weird. I also use the Menu package, and I haven't had any issues with it. 

What you say about the `null` return, it could be caused by a module not yet loaded or something like that.

**Comment by noxify** [comment] 2015-01-17 20:29
Hi @nWidart,

i have also checked your code and everything looks good in my modules.
Debugbar told me also, that the module is loaded ( first Admin, second Users ).

For me it's currently a good workaround to define the available menus globally.
Maybe in the next project I will invest some time to get a better solution or I will use your CMS solution ;)

**Comment by gravitano** [comment] 2015-03-20 04:22
Hi @ahmadina, you can follow @noxify's way to install pingpong/menus in your module. Thanks to @noxify for his explanation :)

**Closed by gravitano** 2015-03-20 04:22 UTC
